status = dict(
    bills=True,
    bill_versions=True,
    sponsors=True,
    actions=True,
    votes=True,
    contributors=['James Falcon <therealfalcon@gmail.com>',
                  'Tim Freund <tim@freunds.net>'],
    notes="""
Special sessions aren't yet parsed.  Vote passage determination needs
work (some action names/passage indicators are ambiguous).  Bills published
exclusively in PDF do not have their various versions tracked.""",
    )


metadata = dict(
    name='Montana',
    abbreviation='mt',
    legislature_name='Montana Legislature',
    upper_chamber_name='Senate',
    lower_chamber_name='House of Representatives',
    upper_chamber_title='Senator',
    lower_chamber_title='Representative',
    upper_chamber_term=4,
    lower_chamber_term=2,
    terms=[
        dict(name='55',
             sessions=['1997'],
             start_year=1997, end_year=1998),
        dict(name='56',
             sessions=['1999',
                       '1999 Special Session',
                       '2000 Special Session'],
             start_year=1999, end_year=2000),
        dict(name='57',
             sessions=['2001',
                       '2002 August Special Session',
                       '2002 September Special Session'],
             start_year=2001, end_year=2002),
        dict(name='58',
             sessions=['2003'],
             start_year=2003, end_year=2004),
        dict(name='59',
             sessions=['2005',
                       '2005 December Special Session'],
             start_year=2005, end_year=2006),
        dict(name='60',
             sessions=['2007',
                       '2007 May Special Session',
                       '2007 September Special Session'],
             start_year=2007, end_year=2008),
        dict(name='61',
             sessions=['2009'],
             start_year=2009, end_year=2010),
        ],
    )
